name: Add report pdf and yaml files to CDN
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Upload file to bucket
        uses: a-sync/s3-uploader@master
        with:
          args: --endpoint-url ${{ secrets.AWS_ENDPOINT_URL }} --acl public-read --exclude '*' --include '*.pdf' --include '*.yaml' --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: "auto"
          S3_KEY: ""
          FILE: corpus
