# This workflow will test the ORKL corpus for compatibility with the schema and formatting rules

name: Go

on:
  pull_request:
    branches:
      - main
    types: ["opened", "edited", "reopened", "synchronize"]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install Tools
        run: make install

      - name: Validate YAML format
        run: yamlfmt -lint corpus/*.yaml

      - name: Validate YAML schema
        run: yajsv -q -s schema.json corpus/*.yaml
